### PR TITLE
Graphics: 4x zoom one-way path signal

### PR DESCRIPTION
**Pull request by J-PIE-314**
As always, if there is anything that needs to be changed, feel free to let me know. 👍

### CODE REVIEW

**Comment by MasterOktagon** [comment]
I like it, but I think the signal looks a bit plain. Could you add some lights at the edges, maybe?

**Comment by J-PIE-314** [comment]
@MasterOktagon Which one of these styles do you like best? Or are you looking for a different style?

Style 1:

signal shine

Style 2:

signals shiny grainy

**Comment by MasterOktagon** [comment]
I think I like the grainy version more. I maybe should do some work on the
semaphore signals again as I am seeing this...

J-PIE-314 ***@***.***> schrieb am Fr., 22. Dez. 2023, 20:04:

**Comment by zephyris** [comment]
Thank you for tackling this! Getting the infrastructure sprites at 4x complete would be great.

However I'm afraid there's quite a few problems with this one. I'm going to be really picky, mostly because these are very important sprites - PBS signals are default signals, and readability of orientation and state is critical for gameplay. Some problems are because the current 1x sprites aren't great, and some are issues with your interpretation.

1. The size is very different to the 1x graphics. The facing straight towards and away views (|) are pretty much correct, same for the - views. The signal head on the diagonal views (\ and /) are ~1px at 1x (4px at 4x) too tall and ~1.5px at 1x (6px at 4x) too wide.
2. The signals are less readable. For the | front-facing view, the light itself probably needs to be be bigger and the glow a bit stronger. For - views, the relative area of red/green is ~4x smaller. For \ / views the colour is essentially invisible. Ideally for the | view facing away from the camera some light bleedthrough (imagine some air vents or something) should show the signal state.

Then, stylistically:
1. Pole shading is wrong. It should be bright on the right. Also, it's low contrast, doesn't have a shading pattern that suggests glossy metal - take a look at the original graphics toyland sugar mine ;). It should also darken near the ground to embed it on the ground tile.
2. The stripe on the back should probably be a sharp stripe rather than a gradient.
3. The signal head doesn't really match in-game lighting/shading, should always be darker in the SW direction... And ideally should be based on palette colours (16, 32, ... 252) for optimal conversion to 8bpp without too much dither.
4. The red in white marker should be (subtly) shaded, darker in the / orientation.
5. Overall detail is low - but that can be tweaked later.

IMO the best opengfx1 sprites are for for the base signals, `base_32bpp.png` in `graphics\signals\64\`, they might be a useful reference.

Hopefully this is useful... You got unlucky and picked a set of sprites that I think are particularly critical to get exactly right!

**Comment by J-PIE-314** [comment]
@zephyris thank you for the in-depth comments, I agree, the minor details are essential. I knew this would be a challenge, and that is why I decided to give it a try. Now I have a clearer understanding the style OpenGFX2, but am not certain how to proceed.
Are you are planning a remake of all of the 1x zoom signals, except for `base_32bpp.png`? If so, what should be made first, the 4x graphics, or the 1x graphics? Do you think I should start working on electric signals by making a 4x zoom version of `base_32bpp.png` as it looks currently?

**Comment by zephyris** [comment]
In general, if the 1x sprites are identical to OpenGFX1 then they're on my list to probably revise. (I think signals, tram tracks, autorail and vehicles are all that is left). But I wouldn't view anything as 100% finished, so any 1x sprite might still change ;)

For the signals I'd recommend tweaking the 1x graphics first, then making 4x to match. But, you can also draw 4x first and downsize - just make sure to work guided by a 4 x 4 px grid to help with the downscaling. Honestly, I'm not sure which would be the easier pipeline be easier for signals...

And I'd definitely use `base_32bpp.png` as the 1x style reference, it's better than the original windows graphics IMO, so probably good to try 4x of those first. Also, original windows and OpenGFX1 use very different signal styles for entry/exit and path based signals - I'd like to understand _why_ before making a final decision on their design.

Hopefully that all makes sense!

**Comment by zephyris** [comment]
Feel free to keep a PR open so I can see what you're trying and give comments. Or post and @ me on the Discord. Very happy to give feedback!

**Comment by J-PIE-314** [comment]
> Feel free to keep a PR open so I can see what you're trying and give comments. Or post and @ me on the Discord. Very happy to give feedback!

I am started a new branch for signal work on my fork of OpenGFX2. You can follow the progress and give feedback there: [https://github.com/J-PIE-314/opengfx2/tree/signal-graphics](url).

**Comment by zephyris** [comment]
I've looked into the entry/exit and path signal design. There's no clear logic for the distinction between original and ogfx1 styles, so I suggest the following.
image
Key design changes from ogfx1 are: entry/exit signals use a green-red-green light combo, distinct from the path signals, and the path signals are shorter.

**Comment by zephyris** [comment]
Have you made any progress here? No pressure, but I've done some trials with svg-derived sprites for signals with a lot of success - is it OK for me to push ahead with that strategy? Shouldn't take me too long now.

**Comment by J-PIE-314** [comment]
I had some ideas but had not yet committed the time to working on them. Your sprites look great. Definitely feel free to keep working on them. :)

**Pull request closed without merging**
