### PR TITLE
Use Asyncio for faster sprite generation

### PR DESCRIPTION
**Pull request by MasterOktagon**
Use python Async library for usage of faster generation of sprites

### CODE REVIEW

**Comment by zephyris** [comment]
This looks good, thank you! I'll test and merge when I'm back from travelling.

The slowest script by far is custom_dither.py - it should be possible to parallelise processing _within_ a single image too: first find sprites (ie. rectangular almost entirely v!=255 regions), do the conversions per sprite, then reassemble into output sprite sheet images. Certainly not necessary, but if you're bored ;)

**Comment by zephyris** [comment]
Is this fully tested? I'm trying a fresh build and am getting errors, eg.:

```
Traceback (most recent call last):
  File "xxx/GitHub/opengfx2-tmp/graphics/terrain_gridoverlay.py", line 75, in <module>       
    tasks.append(grid(key))
NameError: name 'key' is not defined
```

**Comment by MasterOktagon** [comment]
I fixed this, But I forgot to push. I will do that when I am at Home

**Comment by MasterOktagon** [comment]
fixed now

**Comment by zephyris** [comment]
Thanks for contributing this, but I'm going to close this PR as the parallelisation of `custom_dither.py` has solved the major performance problem. `asyncio` may be useful in the future, but for now not necessary.

**Pull request closed without merging**
